### ISSUE TITLE
iPhone

### ISSUE THREAD

**Issue by Homekitworkerx** [joshstrange/eufy-robovac#10]
You mentioned that this works with an Android phone; is there any way to get the localKey with an iPhone and Mac?

**Comment by apexad** [comment]
Mac, yes (using Blue Stacks emulator).  iPhone, no.

You can get both pieces of information by using logcat to "sniff" the data on an android phone OR emulator (like [BlueStacks](https://www.bluestacks.com).
This is known to work on [Eufy Home v2.3.2](https://www.apkmirror.com/apk/anker/eufyhome/eufyhome-2-3-2-release/eufyhome-2-3-2-android-apk-download/) (click the link to download the apk)

> More detailed steps on using logcat:
  
>  1. Close the app on your mobile device
>  2. Connect the device to your laptop and enable USB debugging
>  3. Run adb logcat -e 'tuya.m.my.group.device.list' (assumes you have already installed the Android debug tools)
>  4. Launch the Eufy Home app
>  5. The output lines contain JSON, you're looking for the values of localKey (16 character hex string) and devId (20 character hex string).

**Comment by imsturmdernacht** [comment]
You can use Charles on your PC / Mac as an SSL proxy to log the data traffic when opening the EufyApp. Here you can read out both parameters.
