### ISSUE TITLE
BlueStacks preferences - Platform settings

### ISSUE THREAD

**Issue by redthree** [joshstrange/eufy-robovac#12]
Hello, I don't actually have an issue. Your documentation help me a lot, thanks!

This is just a suggestion. For the BlueStacks method, you could add a mention to check the box for *Enable Android Debug Bridge*, otherwise the `adb` command won't work :/

![image](https://user-images.githubusercontent.com/4129685/96346594-053b7c00-1073-11eb-9c1e-32506654b921.png)

**Comment by apexad** [comment]
done.  Just added a reference to this issue. Thanks.
