### ISSUE TITLE
New Release request

### ISSUE THREAD

**Issue by jeromeof** [joshstrange/eufy-robovac#2]
Hi,
   I see you updated and merged support for the latest RoboVac but I am wondering if you could push an update to NPM as I am using a project called homebridge-eufy-robovac and it is dependent on your changes to work.

Thanks

**Comment by raulfunkie** [comment]
Yes, please. This would be really good!

**Comment by joshstrange** [comment]
I apologize for the delay, it has been published: https://www.npmjs.com/package/eufy-robovac

At some point I should look into Github actions to see about automating the npm publish on release/tag or something like that.
