### ISSUE TITLE
Status call not working // devId 22 char long?

### ISSUE THREAD

**Issue by louis-sicko** [joshstrange/eufy-robovac#31]
hey i grabbed the devid over bluestacks and the recommended eufy app version.
The weird thing is, that the devId has a total length of 22 instead of 20.
I also tried it with the given devId and localKey but the response of the tool was:

<img width="576" alt="image" src="https://user-images.githubusercontent.com/48160610/181288532-f07db463-f32e-428c-9fe0-ff78d416c25d.png">

**Comment by Sef1995** [comment]
I have the same issue, my device id is 20 chars long though.

**Comment by jonnygiger** [comment]
I have the same issue with a 20 char device id, however 3 or 4 attempts it works.
