### ISSUE TITLE
This plugin slows down Homebridge

### ISSUE THREAD

**Issue by LJXXXD** [joshstrange/eufy-robovac#36]
Kept on getting the following error message.

_This plugin slows down Homebridge. The read handler for the characteristic 'On' didn't respond at all!. Please check that you properly call the callback! See https://homebridge.io/w/JtMGR for more info._

Any solutions?

Thanks

**Comment by apexad** [comment]
this is the repo for the generic eufy-robovac package, not the homebridge plugin
